id: P000014
initial_creation_type: ebook
source_metadata:
  title: མགུར་འབུམ་རྡོ་རྗེའི་གླུ།
  authors:
  - མཛད་པ་པོ། ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  layers:
  - book_title
  - author
  - yigchung
  id: SHE-DKR-17
web_metadata:
  title:
    en: The Song of Vajra:The Collected Spiritual Songs
    bo: མགུར་འབུམ་རྡོ་རྗེའི་གླུ།
  collection:
    en: Dilgo Khyentse Series–  Book 17
    bo: དིལ་མགོ་མཁྱེན་བཙེ་གསུང་འབུམ།–  དེབ། ༡༧
  author:
    en: Kyabje Dilgo Khyentse Rinpoche
    bo: ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-DKR-17
  category:
    en: Spiritual Songs
    bo: མགུར།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-DKR-17.epub
  description:
    en: ''
    bo: ''
